version: '3'
services:
## Router
  router01:
    image: mongo:6.0.4
    container_name: router-01
    hostname: router-01
    command: mongos --port 27017 --configdb rs-config-server/mongo-config-01:27017,mongo-config-02:27017,mongo-config-03:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./router/mongodb_cluster_router01_db:/data/db
      - ./router/mongodb_cluster_router01_config:/data/configdb
    networks:
      - mongo-network

  router02:
    image: mongo:6.0.4
    container_name: router-02
    hostname: router-02
    command: mongos --port 27017 --configdb rs-config-server/mongo-config-01:27017,mongo-config-02:27017,mongo-config-03:27017 --bind_ip_all
    volumes:
      - ./router/mongodb_cluster_router02_db:/data/db
      - ./router/mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    networks:
      - mongo-network


## Config Servers
  configsvr01:
    image: mongo:6.0.4
    container_name: mongo-config-01
    hostname: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all
    volumes:
      - ./config/mongodb_cluster_configsvr01_db:/data/db
      - ./config/mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27217:27017
    restart: always
    networks:
      - mongo-network
  
  configsvr02:
    image: mongo:6.0.4
    container_name: mongo-config-02
    hostname: mongo-config-02
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all
    volumes:
      - ./config/mongodb_cluster_configsvr02_db:/data/db
      - ./config/mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27218:27017
    restart: always
    networks:
      - mongo-network
  
  configsvr03:
    image: mongo:6.0.4
    container_name: mongo-config-03
    hostname: mongo-config-03
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all
    volumes:
      - ./config/mongodb_cluster_configsvr03_db:/data/db
      - ./config/mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27219:27017
    restart: always
    networks:
      - mongo-network

## Shards
  ## Shards 01
  shard01-a:
    image: mongo:6.0.4
    container_name: shard-01-node-a
    hostname: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all
    volumes:
      - ./shard/1/mongodb_cluster_shard01_a_db:/data/db
      - ./shard/1/mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27317:27017
    restart: always
    networks:
      - mongo-network

  shard01-b:
    image: mongo:6.0.4
    container_name: shard-01-node-b
    hostname: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all
    volumes:
      - ./shard/1/mongodb_cluster_shard01_b_db:/data/db
      - ./shard/1/mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27318:27017
    restart: always
    networks:
      - mongo-network

  shard01-c:
    image: mongo:6.0.4
    container_name: shard-01-node-c
    hostname: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all
    volumes:
      - ./shard/1/mongodb_cluster_shard01_c_db:/data/db
      - ./shard/1/mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27319:27017
    restart: always
    networks:
      - mongo-network

  ## Shards 02
  shard02-a:
    image: mongo:6.0.4
    container_name: shard-02-node-a
    hostname: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --bind_ip_all
    volumes:
      - ./shard/2/mongodb_cluster_shard02_a_db:/data/db
      - ./shard/2/mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27417:27017
    restart: always
    networks:
      - mongo-network
  shard02-b:
    image: mongo:6.0.4
    container_name: shard-02-node-b
    hostname: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --bind_ip_all
    volumes:
      - ./shard/2/mongodb_cluster_shard02_b_db:/data/db
      - ./shard/2/mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27418:27017
    restart: always
    networks:
      - mongo-network
  shard02-c:
    image: mongo:6.0.4
    container_name: shard-02-node-c
    hostname: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --bind_ip_all
    volumes:
      - ./shard/2/mongodb_cluster_shard02_c_db:/data/db
      - ./shard/2/mongodb_cluster_shard02_c_config:/data/configdb
    ports:
      - 27419:27017
    restart: always
    networks:
      - mongo-network
  mySQL:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - "/my-db:/var/lib/mysql"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge